import keytar from 'keytar';
import {keytarAccount, keytarService} from '../../../utils/services'

export default async (req, res) => {
    const tokens = await keytar.getPassword(keytarService, keytarAccount);
    let accountId = req.query.accountId;
    let portfolioData = {};

    function calculateTotal(positions) {
      let totalValue = 0;
      for (let position of positions) {
        totalValue = totalValue + (position.quote.amount * position.quantity);
      }
      return totalValue.toFixed(2);
    }
    if (process.env.NODE_ENV === "production") {
        //    Add code from brokerage API
    } else {
        let results = [
            {
                currency: 'CAD',
                security_type: 'exchange_traded_fund',
                cds_eligible: true,
                active_date: '2019-01-01',
                inactive_date: null,
                active: true,
                buyable: true,
                sellable: true,
                stock: {
                  allowed_account_types: [Array],
                  asset_category: 'SHARES',
                  avg_daily_volume_last_month: null,
                  country_of_issue: 'CA',
                  description: null,
                  name: 'Vanguard Growth ETF Portfolio the',
                  primary_exchange: 'TSX',
                  primary_exchange_country: 'CA',
                  reuters_attributes: null,
                  secondary_exchanges: [],
                  security_type: 'EXCHANGE_TRADED_FUND',
                  symbol: 'VGRO'
                },
                asset_class: 'other',
                created_by: 'sysadmin',
                default_quote_data_source: 'xignite',
                investment_type: 'unknown',
                is_invalid: null,
                object: 'position',
                price_interface_symbol: null,
                quote_expiry_minutes: 30,
                security_entity: null,
                settlement_period_business_days: 2,
                updated_by: 'sysadmin',
                id: 'sec-s-aaaaaaaaaaa11111111111111111111',
                user_id: 11,
                account_id: 'tfsa-aaaaaaa',
                start_of_day_quantity: 10,
                start_of_day_book_value: { amount: 219.8, currency: 'CAD' },
                start_of_day_market_book_value: { amount: 219.8, currency: 'CAD' },
                book_value: { amount: 219.8, currency: 'CAD' },
                market_book_value: { amount: 219.8, currency: 'CAD' },
                quantity: 10,
                sellable_quantity: 10,
                created_at: '2020-01-01T00:00:00.000Z',
                updated_at: '2020-01-01T00:00:00.000Z',
                book_value_currency: 'CAD',
                start_of_day_book_value_currency: 'CAD',
                start_of_day_market_book_value_currency: 'CAD',
                market_book_value_currency: 'CAD',
                quote: {
                  object: 'spot_quote',
                  security_id: 'sec-s-a1',
                  amount: '26.2500',
                  currency: 'CAD',
                  ask: '26.2500',
                  ask_size: 1000,
                  bid: '26.2400',
                  bid_size: 200,
                  high: '26.4200',
                  last_size: 100,
                  low: '26.1700',
                  open: '26.4200',
                  volume: 125097,
                  previous_close: '26.3500',
                  previous_closed_at: '2020-01-01T00:00:00.000Z',
                  quote_date: '2020-01-01T00:00:00.000Z'
                },
                todays_earnings_baseline_value: { amount: 263.5, currency: 'CAD' }
              },
              {
                currency: 'CAD',
                security_type: 'equity',
                cds_eligible: true,
                active_date: '2013-01-01',
                inactive_date: null,
                active: true,
                buyable: false,
                sellable: true,
                stock: {
                  allowed_account_types: [Array],
                  asset_category: 'SHARES',
                  avg_daily_volume_last_month: '61111.2500',
                  country_of_issue: 'CA',
                  description: null,
                  name: 'Umbrella Corp',
                  primary_exchange: 'TSX-V',
                  primary_exchange_country: 'CA',
                  reuters_attributes: null,
                  secondary_exchanges: [],
                  security_type: 'EQUITY',
                  symbol: 'WORK'
                },
                asset_class: 'individual_stocks',
                created_by: 'sysadmin',
                default_quote_data_source: 'xignite',
                investment_type: 'unknown',
                object: 'position',
                price_interface_symbol: null,
                quote_expiry_minutes: 30,
                security_entity: null,
                settlement_period_business_days: 2,
                skip_sync: false,
                updated_by: 'sysadmin',
                id: 'sec-s-a1',
                user_id: 1111,
                account_id: 'tfsa-aaaaaa',
                start_of_day_quantity: 1000,
                start_of_day_book_value: { amount: 340, currency: 'CAD' },
                start_of_day_market_book_value: { amount: 340, currency: 'CAD' },
                book_value: { amount: 340, currency: 'CAD' },
                market_book_value: { amount: 340, currency: 'CAD' },
                quantity: 1000,
                sellable_quantity: 1000,
                created_at: '2020-01-01T00:00:00.000Z',
                updated_at: '2020-01-01T00:00:00.000Z',
                book_value_currency: 'CAD',
                start_of_day_book_value_currency: 'CAD',
                start_of_day_market_book_value_currency: 'CAD',
                market_book_value_currency: 'CAD',
                sparkline: [ [Object], [Object], [Object], [Object], [Object] ],
                quote: {
                  object: 'spot_quote',
                  security_id: 'sec-s-a2',
                  amount: '0.1600',
                  currency: 'CAD',
                  ask: '0.1650',
                  ask_size: 40500,
                  bid: '0.1600',
                  bid_size: 500,
                  high: '0.1600',
                  last_size: 2500,
                  low: '0.1600',
                  open: '0.1600',
                  volume: 20670,
                  previous_close: '0.1500',
                  previous_closed_at: '2020-01-01T00:00:00.000Z',
                  quote_date: '2020-01-01T00:00:00.000Z'
                },
                todays_earnings_baseline_value: { amount: 150, currency: 'CAD' }
              },
              {
                currency: 'CAD',
                security_type: 'equity',
                cds_eligible: true,
                active_date: '1999-01-25',
                inactive_date: null,
                active: true,
                buyable: true,
                sellable: true,
                stock: {
                  allowed_account_types: [Array],
                  asset_category: 'SHARES',
                  avg_daily_volume_last_month: '1701588.8500',
                  country_of_issue: 'CA',
                  description: null,
                  name: 'Telus Corp.',
                  primary_exchange: 'TSX',
                  primary_exchange_country: 'CA',
                  reuters_attributes: null,
                  secondary_exchanges: [],
                  security_type: 'EQUITY',
                  symbol: 'T'
                },
                asset_class: 'canadian_stocks',
                ca_mutual_fund: null,
                created_by: 'sysadmin',
                default_quote_data_source: 'xignite',
                euro_mutual_fund: null,
                fx_rate: null,
                investment_type: 'equity',
                is_invalid: null,
                management_expense_ratio: null,
                manually_entered_security: null,
                object: 'position',
                price_interface_symbol: 'T.T',
                quote_expiry_minutes: 30,
                security_entity: null,
                settlement_period_business_days: 2,
                skip_sync: false,
                updated_by: 'sysadmin',
                id: 'sec-s-a21',
                user_id: 11,
                account_id: 'tfsa-a1',
                start_of_day_quantity: 10,
                start_of_day_book_value: { amount: 227.2, currency: 'CAD' },
                start_of_day_market_book_value: { amount: 227.2, currency: 'CAD' },
                book_value: { amount: 227.2, currency: 'CAD' },
                market_book_value: { amount: 227.2, currency: 'CAD' },
                quantity: 10,
                sellable_quantity: 10,
                created_at: '2020-01-01T00:00:00.000Z',
                updated_at: '2020-01-01T00:00:00.000Z',
                book_value_currency: 'CAD',
                start_of_day_book_value_currency: 'CAD',
                start_of_day_market_book_value_currency: 'CAD',
                market_book_value_currency: 'CAD',
                quote: {
                  object: 'spot_quote',
                  security_id: 'sec-s-a3',
                  amount: '23.9200',
                  currency: 'CAD',
                  ask: '23.9500',
                  ask_size: 5000,
                  bid: '23.9300',
                  bid_size: 9800,
                  high: '24.2500',
                  last_size: 200,
                  low: '23.9200',
                  open: '24.2500',
                  volume: 1801411,
                  previous_close: '24.2600',
                  previous_closed_at: '2020-01-01T00:00:00.000Z',
                  quote_date: '2020-01-01T00:00:00.000Z'
                },
                todays_earnings_baseline_value: { amount: 242.6, currency: 'CAD' }
              },
              {
                currency: 'USD',
                security_type: 'equity',
                active_date: '2010-06-29',
                inactive_date: null,
                active: true,
                buyable: true,
                sellable: true,
                stock: {
                  allowed_account_types: [Array],
                  asset_category: 'SHARES',
                  avg_daily_volume_last_month: '13642382.6500',
                  country_of_issue: 'US',
                  description: null,
                  name: 'Tesla Inc',
                  primary_exchange: 'NASDAQ',
                  primary_exchange_country: 'US',
                  secondary_exchanges: [],
                  security_type: 'EQUITY',
                  symbol: 'TSLA'
                },
                asset_class: 'us_stocks',
                created_by: 'sysadmin',
                default_quote_data_source: 'xignite',
                investment_type: 'equity',
                object: 'position',
                quote_expiry_minutes: 30,
                settlement_period_business_days: 2,
                updated_by: 'sysadmin',
                id: 'sec-s-a4',
                user_id: 1111,
                account_id: 'tfsa-a1',
                start_of_day_quantity: 1,
                start_of_day_book_value: { amount: 1035.45, currency: 'CAD' },
                start_of_day_market_book_value: { amount: 766.94, currency: 'USD' },
                book_value: { amount: 1035.45, currency: 'CAD' },
                market_book_value: { amount: 766.94, currency: 'USD' },
                quantity: 1,
                sellable_quantity: 1,
                created_at: '2020-01-01T00:00:00.000Z',
                updated_at: '2020-01-01T00:00:00.000Z',
                book_value_currency: 'CAD',
                start_of_day_book_value_currency: 'CAD',
                start_of_day_market_book_value_currency: 'USD',
                market_book_value_currency: 'USD',
                quote: {
                  object: 'spot_quote',
                  security_id: 'sec-s-50cdacc9811f407c8dff52e15be08582',
                  amount: '1025.0500',
                  currency: 'USD',
                  ask: '1025.1300',
                  ask_size: 1600,
                  bid: '1024.5700',
                  bid_size: 800,
                  high: '1027.4800',
                  last_size: 101449,
                  low: '982.5000',
                  open: '991.8800',
                  volume: 18563413,
                  previous_close: '940.6700',
                  previous_closed_at: '2020-01-01T00:00:00.000Z',
                  quote_date: '2020-01-01T00:00:00.000Z'
                },
                todays_earnings_baseline_value: { amount: 940.67, currency: 'USD' }
              },
              {
                currency: 'CAD',
                security_type: 'equity',
                active_date: '2014-11-03',
                inactive_date: null,
                active: true,
                buyable: true,
                sellable: true,
                stock: {
                  allowed_account_types: [Array],
                  asset_category: 'SHARES',
                  avg_daily_volume_last_month: '6949198.7000',
                  country_of_issue: 'CA',
                  description: null,
                  name: 'Air Canada Inc.',
                  primary_exchange: 'TSX',
                  primary_exchange_country: 'CA',
                  reuters_attributes: null,
                  secondary_exchanges: [],
                  security_type: 'EQUITY',
                  symbol: 'AC'
                },
                asset_class: 'individual_stocks',
                ca_mutual_fund: null,
                created_by: 'sysadmin',
                default_quote_data_source: 'xignite',
                euro_mutual_fund: null,
                fx_rate: null,
                investment_type: 'equity',
                is_invalid: null,
                object: 'position',
                price_interface_symbol: null,
                quote_expiry_minutes: 30,
                security_entity: null,
                settlement_period_business_days: 2,
                skip_sync: false,
                updated_by: 'sysadmin',
                id: 'sec-s-a5',
                user_id: 11,
                account_id: 'tfsa-a1',
                start_of_day_quantity: 50,
                start_of_day_book_value: { amount: 2406, currency: 'CAD' },
                start_of_day_market_book_value: { amount: 2406, currency: 'CAD' },
                book_value: { amount: 2406, currency: 'CAD' },
                market_book_value: { amount: 2406, currency: 'CAD' },
                quantity: 50,
                sellable_quantity: 50,
                created_at: '2020-01-01T00:00:00.000Z',
                updated_at: '2020-01-01T00:00:00.000Z',
                book_value_currency: 'CAD',
                start_of_day_book_value_currency: 'CAD',
                start_of_day_market_book_value_currency: 'CAD',
                market_book_value_currency: 'CAD',
                quote: {
                  object: 'spot_quote',
                  security_id: 'sec-s-a7',
                  amount: '19.5100',
                  currency: 'CAD',
                  ask: '19.4900',
                  ask_size: 2400,
                  bid: '19.4800',
                  bid_size: 13000,
                  high: '20.6800',
                  last_size: 100,
                  low: '19.0100',
                  open: '20.5000',
                  volume: 12646157,
                  previous_close: '21.0100',
                  previous_closed_at: '2020-01-01T00:00:00.000Z',
                  quote_date: '2020-01-01T00:00:00.000Z'
                },
                todays_earnings_baseline_value: { amount: 1050.5, currency: 'CAD' }
              }
            ]
        portfolioData.positions = results;
        portfolioData.total = calculateTotal(results);
        res.statusCode = 200;
        res.data = portfolioData;
    }
    return res;
}
